name: InfectedKits
version: 0.5
description:
author: Chaoscrasher & Garth
main: com.jb1services.mc.garth.infectedkits.main.InfectedKitsPlugin
api-version: 1.8

commands:
  ikits:
    description: Allows you to select a kit!
    usage: use /ikit select <kit> to select a kit!
